services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: correpalabras
      POSTGRES_PASSWORD: correpalabras
      POSTGRES_DB: correpalabras
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    command: ["postgres", "-c", "shared_preload_libraries=uuid-ossp"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=correpalabras;Database=correpalabras;Username=correpalabras;Password=correpalabras"

volumes:
  postgres_data:
 