apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: correpalabras-backend-git
  namespace: dev-itlab
  labels:
    app: correpalabras-backend-git
    group: correpalabras-git-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ryu1uga/itlab-Correpalabras-Backend.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
  output:
    to:
      kind: ImageStreamTag
      name: correpalabras-backend-git:latest
  triggers:
    - type: GitHub
      github:
        secret: correpalabras-webhook-secret
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: correpalabras-backend-git:latest
    - type: ConfigChange
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  postCommit: {}
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
