apiVersion: v1
kind: Service
metadata:
  name: correpalabras-backend-git
  namespace: dev-itlab
  labels:
    app: correpalabras-backend-git
    group: correpalabras-git-app
  annotations:
    description: Service for CorrePalabras Backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: correpalabras-backend-git
